apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer
  namespace: cert-manager
spec:
  vault:
    path: pki/sign/inv-dot-gov-dot-ar
    server: http://vault.vault:8200
    auth:
      kubernetes:
        role: issuer
        mountPath: /v1/auth/kubernetes
        secretRef:
          name: issuer-token
          key: token
