apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ifconfig-cert
  namespace: ifconfig
spec:
  secretName: ifconfig-cert
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - ifconfig.inv.gov.ar
  renewBefore: 720h
