apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-cert
  namespace: cert-manager
spec:
  secretName: test-inv-gov-ar
  issuerRef:
    kind: ClusterIssuer
    name: vault-cluster-issuer
  commonName: test.inv.gov.ar
  dnsNames:
  - test.inv.gov.ar
