apiVersion: v1
kind: Secret
metadata:
  name: cluster-issuer-token
  namespace: cert-manager
  annotations:
    kubernetes.io/service-account.name: vault-auth
type: kubernetes.io/service-account-token
